application: ssjcory-udacity-blog
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /users
  script: main.app

- url: /posts
  script: main.app

- url: /auth
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest
