application: ssjcory-udacity-blog
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /register
  script: main.app

- url: /posts
  script: main.app

- url: /post
  script: main.app

- url: /comment
  script: main.app

- url: /login
  script: main.app

- url: /logout
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest
